// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUEwxNI9h1qFr_r2QzAnjMZeO7DOv1OIM',
    appId: '1:664767246844:web:f509a5ca9bb648cca10279',
    messagingSenderId: '664767246844',
    projectId: 'authtutorial-81cc5',
    authDomain: 'authtutorial-81cc5.firebaseapp.com',
    storageBucket: 'authtutorial-81cc5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_YMYM3ZhNrLRTi4hsXnW3cZ1JMoXDCKU',
    appId: '1:664767246844:android:966b1cc7b22ae80ba10279',
    messagingSenderId: '664767246844',
    projectId: 'authtutorial-81cc5',
    storageBucket: 'authtutorial-81cc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB675FCrJV3pej1hcB135WnouE4CHbbYto',
    appId: '1:664767246844:ios:68cf35e2385ec078a10279',
    messagingSenderId: '664767246844',
    projectId: 'authtutorial-81cc5',
    storageBucket: 'authtutorial-81cc5.appspot.com',
    iosClientId: '664767246844-aj15qegjfp71sli8uiippr5t6vcen8hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB675FCrJV3pej1hcB135WnouE4CHbbYto',
    appId: '1:664767246844:ios:6d23325d1e50a0cba10279',
    messagingSenderId: '664767246844',
    projectId: 'authtutorial-81cc5',
    storageBucket: 'authtutorial-81cc5.appspot.com',
    iosClientId: '664767246844-878vrn86bs76o8t655st3b8ssn4ls0hi.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
